name: smart_kitchen_frontend
description: Smart Kitchen Assistant frontend
publish_to: 'none'
version: 0.0.1
environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  http: ^1.5.0
  camera: ^0.11.2+1
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.0.4
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true